/*
 * sysinit.c
 *
 *  Created on: Apr 27, 2020
 *      Author: muaddib
 */

#include "stm32f407xx.h"
#include "sysinit.h"

#define TIM2_TRGO	6
#define GPION_ANALOG_FUNCTION 3

void adc_init(void)
{
	ADC1->CR1 = ADC_CR1_AWDEN | ADC_CR1_AWDSGL | ADC_CR1_SCAN | ADC_CR1_AWDIE;
	//ADC1->CR1 = ADC_CR1_SCAN;

	//EXT on rising edge
	ADC1->CR2 = ADC_CR2_EXTEN_0 | (TIM2_TRGO << ADC_CR2_EXTSEL_Pos) | ADC_CR2_DDS | ADC_CR2_DMA | ADC_CR2_ADON;

	ADC1->HTR = 0x00000fff;
	ADC1->LTR = 0x00000000;

	ADC1->SQR3 = (1 << ADC_SQR3_SQ6_Pos);

	ADC2->CR1 = ADC_CR1_AWDEN | ADC_CR1_AWDSGL | ADC_CR1_SCAN | ADC_CR1_AWDIE;
		//ADC1->CR1 = ADC_CR1_SCAN;

	//EXT on rising edge
	ADC2->CR2 = ADC_CR2_EXTEN_0 | (TIM2_TRGO << ADC_CR2_EXTSEL_Pos) | ADC_CR2_DDS | ADC_CR2_DMA | ADC_CR2_ADON;

	ADC2->HTR = 0x00000fff;
	ADC2->LTR = 0x00000000;

	ADC2->SQR3 = (1 << ADC_SQR3_SQ6_Pos);


	ADC3->CR1 = ADC_CR1_AWDEN | ADC_CR1_AWDSGL | ADC_CR1_SCAN | ADC_CR1_AWDIE;
	//ADC1->CR1 = ADC_CR1_SCAN;

	//EXT on rising edge
	ADC3->CR2 = ADC_CR2_EXTEN_0 | (TIM2_TRGO << ADC_CR2_EXTSEL_Pos) | ADC_CR2_DDS | ADC_CR2_DMA | ADC_CR2_ADON;

	ADC3->HTR = 0x00000fff;
	ADC3->LTR = 0x00000000;

	ADC3->SQR3 = (1 << ADC_SQR3_SQ6_Pos);


	//DMA1 mode
	ADC->CCR = ADC_CCR_DMA_0 | ADC_CCR_DDS;
}

void adc_gpio_init(void)
{
	GPIOA->MODER |= (GPION_ANALOG_FUNCTION << GPIO_MODER_MODER1_Pos) | (GPION_ANALOG_FUNCTION << GPIO_MODER_MODER2_Pos) |
					(GPION_ANALOG_FUNCTION << GPIO_MODER_MODER3_Pos) | (GPION_ANALOG_FUNCTION << GPIO_MODER_MODER4_Pos) |
					(GPION_ANALOG_FUNCTION << GPIO_MODER_MODER5_Pos) | (GPION_ANALOG_FUNCTION << GPIO_MODER_MODER6_Pos);
	GPIOA->PUPDR &= (~GPIO_PUPDR_PUPD1) & (~GPIO_PUPDR_PUPD2) & (~GPIO_PUPDR_PUPD3) & (~GPIO_PUPDR_PUPD4) & (~GPIO_PUPDR_PUPD5) & (~GPIO_PUPDR_PUPD6);
}

void sys_init(void)
{
	adc_gpio_init();
}
